### ISSUE TITLE
Question: is BottomSheetDialogFragment shown small on landscape, on purpose?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ricknout/android-mdc-theming#5]
I've noticed that if you show the BottomSheetDialogFragment via the sample, by clicking on "show modal bottom sheet", while on landscape , it gets shown much smaller:

![image](https://user-images.githubusercontent.com/5357526/58544197-7aea4200-8209-11e9-8a61-faf9d98a5eec.png)

Is this on purpose?
Why does it occur?
Is there an official way to handle this? To know if it's in this state? Is it possible to expand it by default?

The only thing I've found about it, is a workaround as such:
https://stackoverflow.com/a/55713263/878126
but it's not an official solution...

**Comment by ricknout** [comment]
Well spotted @AndroidDeveloperLB, I had not seen this before.

I believe this is because the default modal bottom sheet peek height is `auto`. From the documentation for `BottomSheetBehavior`, this is used:
> to configure the sheet to peek automatically at 16:9 ratio keyline.

which would be less in landscape.

In this repository, you can "fix" this by adding:
`<item name="behavior_peekHeight">100dp</item>`
to the `ModalBottomSheet` style in `styles_bottom_sheet.xml`

**Comment by AndroidDeveloperLB** [comment]
This is automatic?!
It automatically chose really bad height...
So small that in almost all cases that the user sees this, it will be needed to be dragged to see the rest of it.
Isn't there a flag to make it expanded by default?

**Comment by ricknout** [comment]
@AndroidDeveloperLB unfortunately I don't know of any way. It's probably best to file a feature request here: https://issuetracker.google.com/issues/new?component=439535

**Comment by AndroidDeveloperLB** [comment]
OK here:
https://issuetracker.google.com/issues/133782945
